{"name": "新增环境：环境地址必须以http:或 https:开头", "status": "broken", "statusDetails": {"message": "NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Temp\\\\playwright-pytest-q4jazthp\\\\3673a67f496db19aec2f21ab26650468.webm'", "trace": "path = 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Temp\\\\playwright-pytest-q4jazthp'\nonerror = <function TemporaryDirectory._rmtree.<locals>.onerror at 0x0000017179566D30>\n\n    def _rmtree_unsafe(path, onerror):\n        try:\n            with os.scandir(path) as scandir_it:\n                entries = list(scandir_it)\n        except OSError:\n            onerror(os.scandir, path, sys.exc_info())\n            entries = []\n        for entry in entries:\n            fullname = entry.path\n            if _rmtree_isdir(entry):\n                try:\n                    if entry.is_symlink():\n                        # This can only happen if someone replaces\n                        # a directory with a symlink after the call to\n                        # os.scandir or entry.is_dir above.\n                        raise OSError(\"Cannot call rmtree on a symbolic link\")\n                except OSError:\n                    onerror(os.path.islink, fullname, sys.exc_info())\n                    continue\n                _rmtree_unsafe(fullname, onerror)\n            else:\n                try:\n>                   os.unlink(fullname)\nE                   PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Temp\\\\playwright-pytest-q4jazthp\\\\3673a67f496db19aec2f21ab26650468.webm'\n\nD:\\python3.9\\lib\\shutil.py:627: PermissionError\n\nDuring handling of the above exception, another exception occurred:\n\nfunc = <built-in function unlink>\npath = 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Temp\\\\playwright-pytest-q4jazthp\\\\3673a67f496db19aec2f21ab26650468.webm'\nexc_info = (<class 'PermissionError'>, PermissionError(13, '另一个程序正在使用此文件，进程无法访问。'), <traceback object at 0x00000171785E8FC0>)\n\n    def onerror(func, path, exc_info):\n        if issubclass(exc_info[0], PermissionError):\n            def resetperms(path):\n                try:\n                    _os.chflags(path, 0)\n                except AttributeError:\n                    pass\n                _os.chmod(path, 0o700)\n    \n            try:\n                if path != name:\n                    resetperms(_os.path.dirname(path))\n                resetperms(path)\n    \n                try:\n>                   _os.unlink(path)\nE                   PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Temp\\\\playwright-pytest-q4jazthp\\\\3673a67f496db19aec2f21ab26650468.webm'\n\nD:\\python3.9\\lib\\tempfile.py:805: PermissionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <allure_commons._allure.fixture object at 0x000001717862F250>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\nvenv\\lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nplugins\\pytest_playwright.py:199: in browser\n    artifacts_folder.cleanup()\nD:\\python3.9\\lib\\tempfile.py:834: in cleanup\n    self._rmtree(self.name)\nD:\\python3.9\\lib\\tempfile.py:816: in _rmtree\n    _shutil.rmtree(name, onerror=onerror)\nD:\\python3.9\\lib\\shutil.py:759: in rmtree\n    return _rmtree_unsafe(path, onerror)\nD:\\python3.9\\lib\\shutil.py:629: in _rmtree_unsafe\n    onerror(os.unlink, fullname, sys.exc_info())\nD:\\python3.9\\lib\\tempfile.py:808: in onerror\n    cls._rmtree(path)\nD:\\python3.9\\lib\\tempfile.py:816: in _rmtree\n    _shutil.rmtree(name, onerror=onerror)\nD:\\python3.9\\lib\\shutil.py:759: in rmtree\n    return _rmtree_unsafe(path, onerror)\nD:\\python3.9\\lib\\shutil.py:610: in _rmtree_unsafe\n    onerror(os.scandir, path, sys.exc_info())\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\npath = 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Temp\\\\playwright-pytest-q4jazthp\\\\3673a67f496db19aec2f21ab26650468.webm'\nonerror = <function TemporaryDirectory._rmtree.<locals>.onerror at 0x00000171795664C0>\n\n    def _rmtree_unsafe(path, onerror):\n        try:\n>           with os.scandir(path) as scandir_it:\nE           NotADirectoryError: [WinError 267] 目录名称无效。: 'C:\\\\Users\\\\dell\\\\AppData\\\\Local\\\\Temp\\\\playwright-pytest-q4jazthp\\\\3673a67f496db19aec2f21ab26650468.webm'\n\nD:\\python3.9\\lib\\shutil.py:607: NotADirectoryError"}, "description": "新增环境：环境地址必须以http:或 https:开头", "steps": [{"name": "点击添加环境按钮", "status": "passed", "start": 1713511711675, "stop": 1713511711792}, {"name": "模态框输入环境名称: env", "status": "passed", "start": 1713511711953, "stop": 1713511712037}, {"name": "模态框输入环境地址: httpsx://", "status": "passed", "start": 1713511712037, "stop": 1713511712100}, {"name": "点击模态框保存按钮", "status": "passed", "start": 1713511712100, "stop": 1713511712279}], "attachments": [{"name": "stdout", "source": "d9e8147a-6b9a-4f55-8070-96c1b9ed0693-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "browser_name", "value": "'chromium'"}, {"name": "address", "value": "'httpsx://'"}], "start": 1713511711674, "stop": 1713511712704, "uuid": "7b53cabf-4395-462e-ab08-a461a6191991", "historyId": "80180ffcbd97294866b29bffb5dcf15d", "testCaseId": "6e99b035e0b68f45b55b2f9275519e61", "fullName": "cases.test_env_list.TestEnvList#test_add_env_address_invalid", "labels": [{"name": "feature", "value": "环境列表"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "test_env_list"}, {"name": "subSuite", "value": "TestEnvList"}, {"name": "host", "value": "DESKTOP-HJ487C8"}, {"name": "thread", "value": "15308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.test_env_list"}]}